first-commit
DaniilStelmakh/tracker-parcel-go pull request #1
Opened 2024-06-30 11:31 UTC by DaniilStelmakh

2024-07-01 13:57 UTC, dirtymew requested changes
Привет Даниил

отличная работа - все верно реализовано

немного нужно подправить

2024-07-01 13:57 UTC, dirtymew commented on parcel.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-07-01 13:57 UTC, dirtymew commented on parcel_test.go
> +	assert.Equal(t, err, sql.ErrNoRows)
лучше EqualError или ErrorIs

2024-07-09 19:55 UTC, DaniilStelmakh commented
@dirtymew, прошу прощения за задержку)))

2024-07-09 20:34 UTC, dirtymew approved these changes
Привет Даниил

все отлично - зачет

2024-11-14 17:50 UTC, merged